### ISSUE TITLE
Sample set of sane defaults for config files?

### ISSUE THREAD

**Issue by iflowfor8hours** [scoobadog/alpine-seedbox#2]
Is there a starting point for the individual config files for each component? Would be good to have something running out the box, and let users customize as they become more familiar.

**Comment by scoobadog** [comment]
For Transmission and OpenVPN the example files are not really needed as Transmission will create a default configuration on first start and OpenVPN configuration should come from a VPN provider. But for Flexget an example file might be a good idea. The only problem that I can think of is that the way people use Flexget might vary a lot but I think I can come up with a simple generic example.

On second thought I might add a container initialisation step that creates an empty configuration for Flexget if it's missing.

**Comment by scoobadog** [comment]
OpenVPN configuration will be documented once #13 is fixed.
